# This file has been generated by node2nix 1.8.0. Do not edit!

{ nodeEnv, fetchurl, fetchgit, globalBuildInputs ? [ ] }:

let
  sources = {
    "ua-parser-js-0.7.21" = {
      name = "ua-parser-js";
      packageName = "ua-parser-js";
      version = "0.7.21";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.21.tgz";
        sha512 =
          "+O8/qh/Qj8CgC6eYBVBykMrNtp5Gebn4dlGD/kKXVkJNDwyrAwSIqwz8CDf+tsAIWVycKcku6gIXJ0qwx/ZXaQ==";
      };
    };
    "unique-names-generator-4.3.1" = {
      name = "unique-names-generator";
      packageName = "unique-names-generator";
      version = "4.3.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/unique-names-generator/-/unique-names-generator-4.3.1.tgz";
        sha512 =
          "oxkKrDXbwx6I5M963SdfmMH2t8n1OIfYyzoJ25BmDeETlyWAZjTbMXwIEMiQDex4lkD2pqe+9gxDJQAB2IOfDg==";
      };
    };
    "ws-7.3.1" = {
      name = "ws";
      packageName = "ws";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.3.1.tgz";
        sha512 =
          "D3RuNkynyHmEJIpD2qrgVkc9DQ23OrN/moAwZX4L8DfvszsJxpjQuUq3LMx6HoYji9fbIOBY18XWBsAux1ZZUA==";
      };
    };
  };
in {
  "snapdrop-git://github.com/LEXUGE/snapdrop-server.git#76c689558cb3e494add0f33a7848e7efe38ab2a9" =
    nodeEnv.buildNodePackage {
      name = "snapdrop";
      packageName = "snapdrop";
      version = "1.0.0";
      src = fetchgit {
        url = "git://github.com/LEXUGE/snapdrop-server.git";
        rev = "76c689558cb3e494add0f33a7848e7efe38ab2a9";
        sha256 =
          "c6a690a73be960c6bae20c3d6e374b1819d6ccaebc186a5570aece1498938bb5";
      };
      dependencies = [
        sources."ua-parser-js-0.7.21"
        sources."unique-names-generator-4.3.1"
        sources."ws-7.3.1"
      ];
      buildInputs = globalBuildInputs;
      meta = {
        description = "";
        license = "ISC";
      };
      production = true;
      bypassCache = true;
      reconstructLock = true;
    };
}
