# This file has been generated by node2nix 1.8.0. Do not edit!

{ nodeEnv, fetchurl, fetchgit, globalBuildInputs ? [ ] }:

let
  sources = {
    "ua-parser-js-0.7.22" = {
      name = "ua-parser-js";
      packageName = "ua-parser-js";
      version = "0.7.22";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/ua-parser-js/-/ua-parser-js-0.7.22.tgz";
        sha512 =
          "YUxzMjJ5T71w6a8WWVcMGM6YWOTX27rCoIQgLXiWaxqXSx9D7DNjiGWn1aJIRSQ5qr0xuhra77bSIh6voR/46Q==";
      };
    };
    "unique-names-generator-4.3.1" = {
      name = "unique-names-generator";
      packageName = "unique-names-generator";
      version = "4.3.1";
      src = fetchurl {
        url =
          "https://registry.npmjs.org/unique-names-generator/-/unique-names-generator-4.3.1.tgz";
        sha512 =
          "oxkKrDXbwx6I5M963SdfmMH2t8n1OIfYyzoJ25BmDeETlyWAZjTbMXwIEMiQDex4lkD2pqe+9gxDJQAB2IOfDg==";
      };
    };
    "ws-7.3.1" = {
      name = "ws";
      packageName = "ws";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.3.1.tgz";
        sha512 =
          "D3RuNkynyHmEJIpD2qrgVkc9DQ23OrN/moAwZX4L8DfvszsJxpjQuUq3LMx6HoYji9fbIOBY18XWBsAux1ZZUA==";
      };
    };
  };
in {
  "snapdrop-git://github.com/LEXUGE/snapdrop-server.git#48d0b997204457657f495ee8112cc9e8c5639e74" =
    nodeEnv.buildNodePackage {
      name = "snapdrop";
      packageName = "snapdrop";
      version = "1.0.0";
      src = fetchgit {
        url = "git://github.com/LEXUGE/snapdrop-server.git";
        rev = "48d0b997204457657f495ee8112cc9e8c5639e74";
        sha256 =
          "ac41d4cae99950d856aaf398d948deb460f9d5beb554c5ec4686561394502b6a";
      };
      dependencies = [
        sources."ua-parser-js-0.7.22"
        sources."unique-names-generator-4.3.1"
        sources."ws-7.3.1"
      ];
      buildInputs = globalBuildInputs;
      meta = {
        description = "";
        license = "ISC";
      };
      production = true;
      bypassCache = true;
      reconstructLock = true;
    };
}
