name: "Update flake dependencies"
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    if: (startsWith(github.event.head_commit.message, 'update:') || (github.event_name == 'schedule'))
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
        # Configure Nix to enable flakes
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: Update flake.lock
      id: update
      run: nix flake update --recreate-lock-file
    - name: Update script
      run: ./update.sh
    - name: Commit changes
      run: |
        git status
        echo "git status done."
        git config --global user.name 'GitHub Action - Harry Ying'
        git config --global user.email 'LEXUGEyky@outlook.com'
        git diff-index --quiet HEAD || git commit -am "Update flake.lock - automated"
        git push
